name: Android Debug .aab & .apk


##on:
##  pull_request:
#    branches : [ QA ]
#  push :
#      branches : [ QA ]

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release-Build"
        default: "Generate release build"
      testers:
        type: choice
        description: "Select testers"
        options:
          - android
          - internalTesters
          - everyone


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Build with Gradle .apk
        #run: ./gradlew build 
        run: ./gradlew assembleDebug bundleDebug
        
 #     - name: Build with Gradle .aab
 #       run: ./gradlew bundleDebug

      - name: Get release file apk path
        id: releaseApk
        run: echo "apkfile=$(find app/build/outputs/apk/debug/*.apk)" >> $GITHUB_ENV

      - name: Get release file aab path
        id: releaseAab
        run: echo "aabfile=$(find app/build/outputs/bundle/debug/*.aab)" >> $GITHUB_ENV


      - name: Verify paths
        run: |
          echo "AAB file path: ${{ env.aabfile }}"
          echo "APK file path: ${{ env.apkfile }}"
          ls -l ${{ env.aabfile }}
          ls -l ${{ env.apkfile }}


      - name: Upload AAB to Artifacts
        uses: actions/upload-artifact@v3
        with:
           name: release-aab
           path: ${{ env.aabfile }}

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
           name: release-apk
           path: ${{ env.apkfile }}
      
      - name: Zip Files
        uses: papeloto/action-zip@v1
        with:
          files: |
            ${{ env.aabfile }}
            ${{ env.apkfile }}
          dest: app/build/outputs/release-artifacts.zip

          

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
           name: release-artifacts
           path: app/build/outputs/release-artifacts.zip
